import Head from "next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import css from "../styles/home.module.css"
import Service from "../components/Service";
import {client} from "../lib/client";
import Menu from "../components/Menu";

export default function Home({ pizza }) {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" type="image/x-icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero/>
          <Service/>
          <Menu pizza={pizza}/>
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async() => {
  const query = '*[_type == "pizza"]'
  const pizza = await client.fetch(query)
  return {
    props: {
      pizza
    }
  }
}